/* Generated by Yosys 0.27+3 (git sha1 b58664d44, gcc 11.3.0-1ubuntu1~22.04 -fPIC -Os) */

module counter_4bit_2clock(clk0, rst, clk1, \q0[0] , \q0[1] , \q0[2] , \q0[3] , \q1[0] , \q1[1] , \q1[2] , \q1[3] );
  input clk0;
  wire clk0;
  input clk1;
  wire clk1;
  wire n24;
  wire n28;
  wire n32;
  wire n36;
  wire n40;
  wire n44;
  wire n48;
  wire n52;
  output \q0[0] ;
  reg \q0[0]  = 1'h0;
  output \q0[1] ;
  reg \q0[1]  = 1'h0;
  output \q0[2] ;
  reg \q0[2]  = 1'h0;
  output \q0[3] ;
  reg \q0[3]  = 1'h0;
  output \q1[0] ;
  reg \q1[0]  = 1'h0;
  output \q1[1] ;
  reg \q1[1]  = 1'h0;
  output \q1[2] ;
  reg \q1[2]  = 1'h0;
  output \q1[3] ;
  reg \q1[3]  = 1'h0;
  input rst;
  wire rst;
  always @(posedge clk1)
    \q1[0]  <= n24;
  always @(posedge clk1)
    \q1[1]  <= n28;
  always @(posedge clk1)
    \q1[2]  <= n32;
  always @(posedge clk1)
    \q1[3]  <= n36;
  always @(posedge clk1)
    \q0[0]  <= n40;
  always @(posedge clk1)
    \q0[1]  <= n44;
  always @(posedge clk1)
    \q0[2]  <= n48;
  always @(posedge clk1)
    \q0[3]  <= n52;
  assign n44 = 8'h14 >> { \q0[0] , \q0[1] , rst };
  assign n48 = 16'h0708 >> { \q0[2] , rst, \q0[0] , \q0[1]  };
  assign n52 = 32'd8323200 >> { \q0[3] , rst, \q0[0] , \q0[1] , \q0[2]  };
  assign n24 = 4'h1 >> { \q1[0] , rst };
  assign n28 = 8'h14 >> { \q1[0] , \q1[1] , rst };
  assign n32 = 16'h0708 >> { \q1[2] , rst, \q1[0] , \q1[1]  };
  assign n36 = 32'd8323200 >> { \q1[3] , rst, \q1[0] , \q1[1] , \q1[2]  };
  assign n40 = 4'h1 >> { \q0[0] , rst };
endmodule
