/* Generated by Yosys 0.27+3 (git sha1 b58664d44, gcc 11.3.0-1ubuntu1~22.04 -fPIC -Os) */

module counter(clk, reset, \result[0] , \result[1] , \result[2] , \result[3] , \result[4] , \result[5] , \result[6] , \result[7] );
  wire _00_;
  input clk;
  wire clk;
  wire n22;
  wire n26;
  wire n30;
  wire n34;
  wire n38;
  wire n42;
  wire n46;
  wire n50;
  input reset;
  wire reset;
  output \result[0] ;
  reg \result[0]  = 1'h0;
  output \result[1] ;
  reg \result[1]  = 1'h0;
  output \result[2] ;
  reg \result[2]  = 1'h0;
  output \result[3] ;
  reg \result[3]  = 1'h0;
  output \result[4] ;
  reg \result[4]  = 1'h0;
  output \result[5] ;
  reg \result[5]  = 1'h0;
  output \result[6] ;
  reg \result[6]  = 1'h0;
  output \result[7] ;
  reg \result[7]  = 1'h0;
  always @(posedge clk)
    \result[0]  <= n22;
  always @(posedge clk)
    \result[1]  <= n26;
  always @(posedge clk)
    \result[2]  <= n30;
  always @(posedge clk)
    \result[3]  <= n34;
  always @(posedge clk)
    \result[4]  <= n38;
  always @(posedge clk)
    \result[5]  <= n42;
  always @(posedge clk)
    \result[6]  <= n46;
  always @(posedge clk)
    \result[7]  <= n50;
  assign n30 = 8'h78 >> { \result[2] , \result[0] , \result[1]  };
  assign n34 = 16'h7f80 >> { \result[3] , \result[0] , \result[1] , \result[2]  };
  assign n38 = 32'd2147450880 >> { \result[4] , \result[0] , \result[1] , \result[2] , \result[3]  };
  assign n42 = 64'h7fffffff80000000 >> { \result[5] , \result[0] , \result[1] , \result[2] , \result[3] , \result[4]  };
  assign n46 = 4'h6 >> { _00_, \result[6]  };
  assign _00_ = 64'h8000000000000000 >> { \result[0] , \result[1] , \result[2] , \result[3] , \result[4] , \result[5]  };
  assign n50 = 8'h78 >> { \result[7] , _00_, \result[6]  };
  assign n22 = 2'h1 >> \result[0] ;
  assign n26 = 4'h6 >> { \result[0] , \result[1]  };
endmodule
