/* Generated by Yosys 0.27+3 (git sha1 b58664d44, gcc 11.3.0-1ubuntu1~22.04 -fPIC -Os) */

module top(clock, in, out);
  input clock;
  wire clock;
  input in;
  wire in;
  wire n7;
  output out;
  reg out;
  always @(posedge clock)
    out <= n7;
  assign n7 = in;
endmodule
